import { writable } from 'svelte/store';

export const mapConfig = writable({
	title: '[This is the map title]',
	subtitle: '[This is the map subtitle]',
	datasetType: 'values',
	datasetUnit: 'fullNumbers',
	percentRounded: false,
	colourSchemeType: 'sequential',
	colourScheme: 'red',
	colourSchemeClasses: 5,
	colourSchemeReverse: false,
	overrideScaleValues: false,
	colorBarFirstValue: undefined,
	colorBarLastValue: undefined,
	headlineAvailable: true,
	subheadlineAvailable: true,
	tooltipAvailable: true,
	scaleBarAvailable: true,
	legendAvailable: true,
	textSourceAvailable: true,
	textSource: '',
	textNoteAvailable: true,
	textNote: '',
	textDataAccessAvailable: true,
	linkDataAccess: '',
	legend1Color: '#F4F4F4',
	legend2Color: 'red',
	legend3Color: 'blue',
	legend4Color: 'green',
	parsedData: null,
	data: `country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url
Austria,AT,35,FALSE,,,,,,,,,
Belgium,BE,83,FALSE,,,,,,,,,
Bulgaria,BG,25,FALSE,,,,,,,,,
Cyprus,CY,57,FALSE,,,,,,,,,
Czechia,CZ,23,FALSE,,,,,,,,,
Germany,DE,41,FALSE,,,,,,,,,
Denmark,DK,36,FALSE,,,,,,,,,
Estonia,EE,47,FALSE,,,,,,,,,
Greece,EL,16,FALSE,,,,,,,,,
Spain,ES,32,FALSE,,,,,,,,,
Finland,FI,91,FALSE,,,,,,,,,
France,FR,45,FALSE,,,,,,,,,
Croatia,HR,23,FALSE,,,,,,,,,
Hungary,HU,19,FALSE,,,,,,,,,
Ireland,IE,43,FALSE,,,,,,,,,
Italy,IT,6,FALSE,,,,,,,,,
Lithuania,LT,72,FALSE,,,,,,,,,
Luxembourg,LU,39,FALSE,,,,,,,,,
Latvia,LV,33,FALSE,,,,,,,,,
Malta,MT,45,FALSE,,,,,,,,,
Netherlands,NL,12,FALSE,,,,,,,,,
Poland,PL,74,FALSE,,,,,,,,,
Portugal,PT,48,FALSE,,,,,,,,,
Romania,RO,92,FALSE,,,,,,,,,
Sweden,SE,23,FALSE,,,,,,,,,
Slovenia,SI,24,FALSE,,,,,,,,,
Slovakia,SK,66,FALSE,,,,,,,,,`
});
